// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_user_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_user_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_user_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal
{
  class AnyMetadata;
} // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_user_2eproto
{
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_user_2eproto;
namespace user
{
  class CreateUserRequest;
  struct CreateUserRequestDefaultTypeInternal;
  extern CreateUserRequestDefaultTypeInternal _CreateUserRequest_default_instance_;
  class DeleteUserRequest;
  struct DeleteUserRequestDefaultTypeInternal;
  extern DeleteUserRequestDefaultTypeInternal _DeleteUserRequest_default_instance_;
  class DeleteUserResponse;
  struct DeleteUserResponseDefaultTypeInternal;
  extern DeleteUserResponseDefaultTypeInternal _DeleteUserResponse_default_instance_;
  class GetUserRequest;
  struct GetUserRequestDefaultTypeInternal;
  extern GetUserRequestDefaultTypeInternal _GetUserRequest_default_instance_;
  class UpdateUserRequest;
  struct UpdateUserRequestDefaultTypeInternal;
  extern UpdateUserRequestDefaultTypeInternal _UpdateUserRequest_default_instance_;
  class User;
  struct UserDefaultTypeInternal;
  extern UserDefaultTypeInternal _User_default_instance_;
  class UserList;
  struct UserListDefaultTypeInternal;
  extern UserListDefaultTypeInternal _UserList_default_instance_;
  class UserResponse;
  struct UserResponseDefaultTypeInternal;
  extern UserResponseDefaultTypeInternal _UserResponse_default_instance_;
} // namespace user
PROTOBUF_NAMESPACE_OPEN
template <>
::user::CreateUserRequest *Arena::CreateMaybeMessage<::user::CreateUserRequest>(Arena *);
template <>
::user::DeleteUserRequest *Arena::CreateMaybeMessage<::user::DeleteUserRequest>(Arena *);
template <>
::user::DeleteUserResponse *Arena::CreateMaybeMessage<::user::DeleteUserResponse>(Arena *);
template <>
::user::GetUserRequest *Arena::CreateMaybeMessage<::user::GetUserRequest>(Arena *);
template <>
::user::UpdateUserRequest *Arena::CreateMaybeMessage<::user::UpdateUserRequest>(Arena *);
template <>
::user::User *Arena::CreateMaybeMessage<::user::User>(Arena *);
template <>
::user::UserList *Arena::CreateMaybeMessage<::user::UserList>(Arena *);
template <>
::user::UserResponse *Arena::CreateMaybeMessage<::user::UserResponse>(Arena *);
PROTOBUF_NAMESPACE_CLOSE
namespace user
{

  // ===================================================================

  class User final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.User) */
  {
  public:
    inline User() : User(nullptr) {}
    ~User() override;
    explicit PROTOBUF_CONSTEXPR User(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    User(const User &from);
    User(User &&from) noexcept
        : User()
    {
      *this = ::std::move(from);
    }

    inline User &operator=(const User &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline User &operator=(User &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const User &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const User *internal_default_instance()
    {
      return reinterpret_cast<const User *>(
          &_User_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        0;

    friend void swap(User &a, User &b)
    {
      a.Swap(&b);
    }
    inline void Swap(User *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(User *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    User *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<User>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const User &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const User &from)
    {
      User::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(User *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.User";
    }

  protected:
    explicit User(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                  bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kNameFieldNumber = 2,
      kEmailFieldNumber = 3,
      kIdFieldNumber = 1,
    };
    // string name = 2;
    void clear_name();
    const std::string &name() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_name(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_name();
    PROTOBUF_NODISCARD std::string *release_name();
    void set_allocated_name(std::string *name);

  private:
    const std::string &_internal_name() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string &value);
    std::string *_internal_mutable_name();

  public:
    // string email = 3;
    void clear_email();
    const std::string &email() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_email(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_email();
    PROTOBUF_NODISCARD std::string *release_email();
    void set_allocated_email(std::string *email);

  private:
    const std::string &_internal_email() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string &value);
    std::string *_internal_mutable_email();

  public:
    // int32 id = 1;
    void clear_id();
    int32_t id() const;
    void set_id(int32_t value);

  private:
    int32_t _internal_id() const;
    void _internal_set_id(int32_t value);

  public:
    // @@protoc_insertion_point(class_scope:user.User)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
      int32_t id_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // -------------------------------------------------------------------

  class CreateUserRequest final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.CreateUserRequest) */
  {
  public:
    inline CreateUserRequest() : CreateUserRequest(nullptr) {}
    ~CreateUserRequest() override;
    explicit PROTOBUF_CONSTEXPR CreateUserRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    CreateUserRequest(const CreateUserRequest &from);
    CreateUserRequest(CreateUserRequest &&from) noexcept
        : CreateUserRequest()
    {
      *this = ::std::move(from);
    }

    inline CreateUserRequest &operator=(const CreateUserRequest &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline CreateUserRequest &operator=(CreateUserRequest &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const CreateUserRequest &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const CreateUserRequest *internal_default_instance()
    {
      return reinterpret_cast<const CreateUserRequest *>(
          &_CreateUserRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        1;

    friend void swap(CreateUserRequest &a, CreateUserRequest &b)
    {
      a.Swap(&b);
    }
    inline void Swap(CreateUserRequest *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(CreateUserRequest *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    CreateUserRequest *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<CreateUserRequest>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const CreateUserRequest &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const CreateUserRequest &from)
    {
      CreateUserRequest::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(CreateUserRequest *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.CreateUserRequest";
    }

  protected:
    explicit CreateUserRequest(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                               bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kNameFieldNumber = 1,
      kEmailFieldNumber = 2,
    };
    // string name = 1;
    void clear_name();
    const std::string &name() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_name(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_name();
    PROTOBUF_NODISCARD std::string *release_name();
    void set_allocated_name(std::string *name);

  private:
    const std::string &_internal_name() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string &value);
    std::string *_internal_mutable_name();

  public:
    // string email = 2;
    void clear_email();
    const std::string &email() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_email(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_email();
    PROTOBUF_NODISCARD std::string *release_email();
    void set_allocated_email(std::string *email);

  private:
    const std::string &_internal_email() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string &value);
    std::string *_internal_mutable_email();

  public:
    // @@protoc_insertion_point(class_scope:user.CreateUserRequest)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // -------------------------------------------------------------------

  class GetUserRequest final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.GetUserRequest) */
  {
  public:
    inline GetUserRequest() : GetUserRequest(nullptr) {}
    ~GetUserRequest() override;
    explicit PROTOBUF_CONSTEXPR GetUserRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    GetUserRequest(const GetUserRequest &from);
    GetUserRequest(GetUserRequest &&from) noexcept
        : GetUserRequest()
    {
      *this = ::std::move(from);
    }

    inline GetUserRequest &operator=(const GetUserRequest &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline GetUserRequest &operator=(GetUserRequest &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const GetUserRequest &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const GetUserRequest *internal_default_instance()
    {
      return reinterpret_cast<const GetUserRequest *>(
          &_GetUserRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        2;

    friend void swap(GetUserRequest &a, GetUserRequest &b)
    {
      a.Swap(&b);
    }
    inline void Swap(GetUserRequest *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(GetUserRequest *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    GetUserRequest *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<GetUserRequest>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const GetUserRequest &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const GetUserRequest &from)
    {
      GetUserRequest::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(GetUserRequest *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.GetUserRequest";
    }

  protected:
    explicit GetUserRequest(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                            bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kIdFieldNumber = 1,
    };
    // int32 id = 1;
    void clear_id();
    int32_t id() const;
    void set_id(int32_t value);

  private:
    int32_t _internal_id() const;
    void _internal_set_id(int32_t value);

  public:
    // @@protoc_insertion_point(class_scope:user.GetUserRequest)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      int32_t id_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // -------------------------------------------------------------------

  class DeleteUserRequest final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.DeleteUserRequest) */
  {
  public:
    inline DeleteUserRequest() : DeleteUserRequest(nullptr) {}
    ~DeleteUserRequest() override;
    explicit PROTOBUF_CONSTEXPR DeleteUserRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    DeleteUserRequest(const DeleteUserRequest &from);
    DeleteUserRequest(DeleteUserRequest &&from) noexcept
        : DeleteUserRequest()
    {
      *this = ::std::move(from);
    }

    inline DeleteUserRequest &operator=(const DeleteUserRequest &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline DeleteUserRequest &operator=(DeleteUserRequest &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const DeleteUserRequest &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const DeleteUserRequest *internal_default_instance()
    {
      return reinterpret_cast<const DeleteUserRequest *>(
          &_DeleteUserRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        3;

    friend void swap(DeleteUserRequest &a, DeleteUserRequest &b)
    {
      a.Swap(&b);
    }
    inline void Swap(DeleteUserRequest *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(DeleteUserRequest *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    DeleteUserRequest *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<DeleteUserRequest>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const DeleteUserRequest &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const DeleteUserRequest &from)
    {
      DeleteUserRequest::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(DeleteUserRequest *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.DeleteUserRequest";
    }

  protected:
    explicit DeleteUserRequest(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                               bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kIdFieldNumber = 1,
    };
    // int32 id = 1;
    void clear_id();
    int32_t id() const;
    void set_id(int32_t value);

  private:
    int32_t _internal_id() const;
    void _internal_set_id(int32_t value);

  public:
    // @@protoc_insertion_point(class_scope:user.DeleteUserRequest)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      int32_t id_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // -------------------------------------------------------------------

  class UserResponse final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.UserResponse) */
  {
  public:
    inline UserResponse() : UserResponse(nullptr) {}
    ~UserResponse() override;
    explicit PROTOBUF_CONSTEXPR UserResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    UserResponse(const UserResponse &from);
    UserResponse(UserResponse &&from) noexcept
        : UserResponse()
    {
      *this = ::std::move(from);
    }

    inline UserResponse &operator=(const UserResponse &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline UserResponse &operator=(UserResponse &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const UserResponse &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const UserResponse *internal_default_instance()
    {
      return reinterpret_cast<const UserResponse *>(
          &_UserResponse_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        4;

    friend void swap(UserResponse &a, UserResponse &b)
    {
      a.Swap(&b);
    }
    inline void Swap(UserResponse *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(UserResponse *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    UserResponse *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<UserResponse>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const UserResponse &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const UserResponse &from)
    {
      UserResponse::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(UserResponse *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.UserResponse";
    }

  protected:
    explicit UserResponse(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                          bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kUserFieldNumber = 1,
    };
    // .user.User user = 1;
    bool has_user() const;

  private:
    bool _internal_has_user() const;

  public:
    void clear_user();
    const ::user::User &user() const;
    PROTOBUF_NODISCARD ::user::User *release_user();
    ::user::User *mutable_user();
    void set_allocated_user(::user::User *user);

  private:
    const ::user::User &_internal_user() const;
    ::user::User *_internal_mutable_user();

  public:
    void unsafe_arena_set_allocated_user(
        ::user::User *user);
    ::user::User *unsafe_arena_release_user();

    // @@protoc_insertion_point(class_scope:user.UserResponse)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      ::user::User *user_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // -------------------------------------------------------------------

  class DeleteUserResponse final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.DeleteUserResponse) */
  {
  public:
    inline DeleteUserResponse() : DeleteUserResponse(nullptr) {}
    ~DeleteUserResponse() override;
    explicit PROTOBUF_CONSTEXPR DeleteUserResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    DeleteUserResponse(const DeleteUserResponse &from);
    DeleteUserResponse(DeleteUserResponse &&from) noexcept
        : DeleteUserResponse()
    {
      *this = ::std::move(from);
    }

    inline DeleteUserResponse &operator=(const DeleteUserResponse &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline DeleteUserResponse &operator=(DeleteUserResponse &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const DeleteUserResponse &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const DeleteUserResponse *internal_default_instance()
    {
      return reinterpret_cast<const DeleteUserResponse *>(
          &_DeleteUserResponse_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        5;

    friend void swap(DeleteUserResponse &a, DeleteUserResponse &b)
    {
      a.Swap(&b);
    }
    inline void Swap(DeleteUserResponse *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(DeleteUserResponse *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    DeleteUserResponse *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<DeleteUserResponse>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const DeleteUserResponse &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const DeleteUserResponse &from)
    {
      DeleteUserResponse::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(DeleteUserResponse *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.DeleteUserResponse";
    }

  protected:
    explicit DeleteUserResponse(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                                bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kSuccessFieldNumber = 1,
    };
    // bool success = 1;
    void clear_success();
    bool success() const;
    void set_success(bool value);

  private:
    bool _internal_success() const;
    void _internal_set_success(bool value);

  public:
    // @@protoc_insertion_point(class_scope:user.DeleteUserResponse)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      bool success_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // -------------------------------------------------------------------

  class UserList final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.UserList) */
  {
  public:
    inline UserList() : UserList(nullptr) {}
    ~UserList() override;
    explicit PROTOBUF_CONSTEXPR UserList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    UserList(const UserList &from);
    UserList(UserList &&from) noexcept
        : UserList()
    {
      *this = ::std::move(from);
    }

    inline UserList &operator=(const UserList &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline UserList &operator=(UserList &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const UserList &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const UserList *internal_default_instance()
    {
      return reinterpret_cast<const UserList *>(
          &_UserList_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        6;

    friend void swap(UserList &a, UserList &b)
    {
      a.Swap(&b);
    }
    inline void Swap(UserList *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(UserList *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    UserList *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<UserList>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const UserList &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const UserList &from)
    {
      UserList::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(UserList *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.UserList";
    }

  protected:
    explicit UserList(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                      bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kUsersFieldNumber = 1,
    };
    // repeated .user.User users = 1;
    int users_size() const;

  private:
    int _internal_users_size() const;

  public:
    void clear_users();
    ::user::User *mutable_users(int index);
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::user::User> *
    mutable_users();

  private:
    const ::user::User &_internal_users(int index) const;
    ::user::User *_internal_add_users();

  public:
    const ::user::User &users(int index) const;
    ::user::User *add_users();
    const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::user::User> &
    users() const;

    // @@protoc_insertion_point(class_scope:user.UserList)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::user::User> users_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // -------------------------------------------------------------------

  class UpdateUserRequest final : public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:user.UpdateUserRequest) */
  {
  public:
    inline UpdateUserRequest() : UpdateUserRequest(nullptr) {}
    ~UpdateUserRequest() override;
    explicit PROTOBUF_CONSTEXPR UpdateUserRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

    UpdateUserRequest(const UpdateUserRequest &from);
    UpdateUserRequest(UpdateUserRequest &&from) noexcept
        : UpdateUserRequest()
    {
      *this = ::std::move(from);
    }

    inline UpdateUserRequest &operator=(const UpdateUserRequest &from)
    {
      CopyFrom(from);
      return *this;
    }
    inline UpdateUserRequest &operator=(UpdateUserRequest &&from) noexcept
    {
      if (this == &from)
        return *this;
      if (GetOwningArena() == from.GetOwningArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
          && GetOwningArena() != nullptr
#endif // !PROTOBUF_FORCE_COPY_IN_MOVE
      )
      {
        InternalSwap(&from);
      }
      else
      {
        CopyFrom(from);
      }
      return *this;
    }

    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *descriptor()
    {
      return GetDescriptor();
    }
    static const ::PROTOBUF_NAMESPACE_ID::Descriptor *GetDescriptor()
    {
      return default_instance().GetMetadata().descriptor;
    }
    static const ::PROTOBUF_NAMESPACE_ID::Reflection *GetReflection()
    {
      return default_instance().GetMetadata().reflection;
    }
    static const UpdateUserRequest &default_instance()
    {
      return *internal_default_instance();
    }
    static inline const UpdateUserRequest *internal_default_instance()
    {
      return reinterpret_cast<const UpdateUserRequest *>(
          &_UpdateUserRequest_default_instance_);
    }
    static constexpr int kIndexInFileMessages =
        7;

    friend void swap(UpdateUserRequest &a, UpdateUserRequest &b)
    {
      a.Swap(&b);
    }
    inline void Swap(UpdateUserRequest *other)
    {
      if (other == this)
        return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() != nullptr &&
          GetOwningArena() == other->GetOwningArena())
      {
#else  // PROTOBUF_FORCE_COPY_IN_SWAP
      if (GetOwningArena() == other->GetOwningArena())
      {
#endif // !PROTOBUF_FORCE_COPY_IN_SWAP
        InternalSwap(other);
      }
      else
      {
        ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
      }
    }
    void UnsafeArenaSwap(UpdateUserRequest *other)
    {
      if (other == this)
        return;
      GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
      InternalSwap(other);
    }

    // implements Message ----------------------------------------------

    UpdateUserRequest *New(::PROTOBUF_NAMESPACE_ID::Arena *arena = nullptr) const final
    {
      return CreateMaybeMessage<UpdateUserRequest>(arena);
    }
    using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
    void CopyFrom(const UpdateUserRequest &from);
    using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
    void MergeFrom(const UpdateUserRequest &from)
    {
      UpdateUserRequest::MergeImpl(*this, from);
    }

  private:
    static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message &to_msg, const ::PROTOBUF_NAMESPACE_ID::Message &from_msg);

  public:
    PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
    bool IsInitialized() const final;

    size_t ByteSizeLong() const final;
    const char *_InternalParse(const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final;
    uint8_t *_InternalSerialize(
        uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final;
    int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
    void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned);
    void SharedDtor();
    void SetCachedSize(int size) const final;
    void InternalSwap(UpdateUserRequest *other);

  private:
    friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
    static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName()
    {
      return "user.UpdateUserRequest";
    }

  protected:
    explicit UpdateUserRequest(::PROTOBUF_NAMESPACE_ID::Arena *arena,
                               bool is_message_owned = false);

  public:
    static const ClassData _class_data_;
    const ::PROTOBUF_NAMESPACE_ID::Message::ClassData *GetClassData() const final;

    ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

    // nested types ----------------------------------------------------

    // accessors -------------------------------------------------------

    enum : int
    {
      kNameFieldNumber = 2,
      kEmailFieldNumber = 3,
      kIdFieldNumber = 1,
    };
    // string name = 2;
    void clear_name();
    const std::string &name() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_name(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_name();
    PROTOBUF_NODISCARD std::string *release_name();
    void set_allocated_name(std::string *name);

  private:
    const std::string &_internal_name() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string &value);
    std::string *_internal_mutable_name();

  public:
    // string email = 3;
    void clear_email();
    const std::string &email() const;
    template <typename ArgT0 = const std::string &, typename... ArgT>
    void set_email(ArgT0 &&arg0, ArgT... args);
    std::string *mutable_email();
    PROTOBUF_NODISCARD std::string *release_email();
    void set_allocated_email(std::string *email);

  private:
    const std::string &_internal_email() const;
    inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string &value);
    std::string *_internal_mutable_email();

  public:
    // int32 id = 1;
    void clear_id();
    int32_t id() const;
    void set_id(int32_t value);

  private:
    int32_t _internal_id() const;
    void _internal_set_id(int32_t value);

  public:
    // @@protoc_insertion_point(class_scope:user.UpdateUserRequest)
  private:
    class _Internal;

    template <typename T>
    friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
    typedef void InternalArenaConstructable_;
    typedef void DestructorSkippable_;
    struct Impl_
    {
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
      int32_t id_;
      mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    };
    union
    {
      Impl_ _impl_;
    };
    friend struct ::TableStruct_user_2eproto;
  };
  // ===================================================================

  // ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
  // User

  // int32 id = 1;
  inline void User::clear_id()
  {
    _impl_.id_ = 0;
  }
  inline int32_t User::_internal_id() const
  {
    return _impl_.id_;
  }
  inline int32_t User::id() const
  {
    // @@protoc_insertion_point(field_get:user.User.id)
    return _internal_id();
  }
  inline void User::_internal_set_id(int32_t value)
  {

    _impl_.id_ = value;
  }
  inline void User::set_id(int32_t value)
  {
    _internal_set_id(value);
    // @@protoc_insertion_point(field_set:user.User.id)
  }

  // string name = 2;
  inline void User::clear_name()
  {
    _impl_.name_.ClearToEmpty();
  }
  inline const std::string &User::name() const
  {
    // @@protoc_insertion_point(field_get:user.User.name)
    return _internal_name();
  }
  template <typename ArgT0, typename... ArgT>
  inline PROTOBUF_ALWAYS_INLINE void User::set_name(ArgT0 &&arg0, ArgT... args)
  {

    _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:user.User.name)
  }
  inline std::string *User::mutable_name()
  {
    std::string *_s = _internal_mutable_name();
    // @@protoc_insertion_point(field_mutable:user.User.name)
    return _s;
  }
  inline const std::string &User::_internal_name() const
  {
    return _impl_.name_.Get();
  }
  inline void User::_internal_set_name(const std::string &value)
  {

    _impl_.name_.Set(value, GetArenaForAllocation());
  }
  inline std::string *User::_internal_mutable_name()
  {

    return _impl_.name_.Mutable(GetArenaForAllocation());
  }
  inline std::string *User::release_name()
  {
    // @@protoc_insertion_point(field_release:user.User.name)
    return _impl_.name_.Release();
  }
  inline void User::set_allocated_name(std::string *name)
  {
    if (name != nullptr)
    {
    }
    else
    {
    }
    _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.name_.IsDefault())
    {
      _impl_.name_.Set("", GetArenaForAllocation());
    }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:user.User.name)
  }

  // string email = 3;
  inline void User::clear_email()
  {
    _impl_.email_.ClearToEmpty();
  }
  inline const std::string &User::email() const
  {
    // @@protoc_insertion_point(field_get:user.User.email)
    return _internal_email();
  }
  template <typename ArgT0, typename... ArgT>
  inline PROTOBUF_ALWAYS_INLINE void User::set_email(ArgT0 &&arg0, ArgT... args)
  {

    _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:user.User.email)
  }
  inline std::string *User::mutable_email()
  {
    std::string *_s = _internal_mutable_email();
    // @@protoc_insertion_point(field_mutable:user.User.email)
    return _s;
  }
  inline const std::string &User::_internal_email() const
  {
    return _impl_.email_.Get();
  }
  inline void User::_internal_set_email(const std::string &value)
  {

    _impl_.email_.Set(value, GetArenaForAllocation());
  }
  inline std::string *User::_internal_mutable_email()
  {

    return _impl_.email_.Mutable(GetArenaForAllocation());
  }
  inline std::string *User::release_email()
  {
    // @@protoc_insertion_point(field_release:user.User.email)
    return _impl_.email_.Release();
  }
  inline void User::set_allocated_email(std::string *email)
  {
    if (email != nullptr)
    {
    }
    else
    {
    }
    _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.email_.IsDefault())
    {
      _impl_.email_.Set("", GetArenaForAllocation());
    }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:user.User.email)
  }

  // -------------------------------------------------------------------

  // CreateUserRequest

  // string name = 1;
  inline void CreateUserRequest::clear_name()
  {
    _impl_.name_.ClearToEmpty();
  }
  inline const std::string &CreateUserRequest::name() const
  {
    // @@protoc_insertion_point(field_get:user.CreateUserRequest.name)
    return _internal_name();
  }
  template <typename ArgT0, typename... ArgT>
  inline PROTOBUF_ALWAYS_INLINE void CreateUserRequest::set_name(ArgT0 &&arg0, ArgT... args)
  {

    _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:user.CreateUserRequest.name)
  }
  inline std::string *CreateUserRequest::mutable_name()
  {
    std::string *_s = _internal_mutable_name();
    // @@protoc_insertion_point(field_mutable:user.CreateUserRequest.name)
    return _s;
  }
  inline const std::string &CreateUserRequest::_internal_name() const
  {
    return _impl_.name_.Get();
  }
  inline void CreateUserRequest::_internal_set_name(const std::string &value)
  {

    _impl_.name_.Set(value, GetArenaForAllocation());
  }
  inline std::string *CreateUserRequest::_internal_mutable_name()
  {

    return _impl_.name_.Mutable(GetArenaForAllocation());
  }
  inline std::string *CreateUserRequest::release_name()
  {
    // @@protoc_insertion_point(field_release:user.CreateUserRequest.name)
    return _impl_.name_.Release();
  }
  inline void CreateUserRequest::set_allocated_name(std::string *name)
  {
    if (name != nullptr)
    {
    }
    else
    {
    }
    _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.name_.IsDefault())
    {
      _impl_.name_.Set("", GetArenaForAllocation());
    }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:user.CreateUserRequest.name)
  }

  // string email = 2;
  inline void CreateUserRequest::clear_email()
  {
    _impl_.email_.ClearToEmpty();
  }
  inline const std::string &CreateUserRequest::email() const
  {
    // @@protoc_insertion_point(field_get:user.CreateUserRequest.email)
    return _internal_email();
  }
  template <typename ArgT0, typename... ArgT>
  inline PROTOBUF_ALWAYS_INLINE void CreateUserRequest::set_email(ArgT0 &&arg0, ArgT... args)
  {

    _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:user.CreateUserRequest.email)
  }
  inline std::string *CreateUserRequest::mutable_email()
  {
    std::string *_s = _internal_mutable_email();
    // @@protoc_insertion_point(field_mutable:user.CreateUserRequest.email)
    return _s;
  }
  inline const std::string &CreateUserRequest::_internal_email() const
  {
    return _impl_.email_.Get();
  }
  inline void CreateUserRequest::_internal_set_email(const std::string &value)
  {

    _impl_.email_.Set(value, GetArenaForAllocation());
  }
  inline std::string *CreateUserRequest::_internal_mutable_email()
  {

    return _impl_.email_.Mutable(GetArenaForAllocation());
  }
  inline std::string *CreateUserRequest::release_email()
  {
    // @@protoc_insertion_point(field_release:user.CreateUserRequest.email)
    return _impl_.email_.Release();
  }
  inline void CreateUserRequest::set_allocated_email(std::string *email)
  {
    if (email != nullptr)
    {
    }
    else
    {
    }
    _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.email_.IsDefault())
    {
      _impl_.email_.Set("", GetArenaForAllocation());
    }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:user.CreateUserRequest.email)
  }

  // -------------------------------------------------------------------

  // GetUserRequest

  // int32 id = 1;
  inline void GetUserRequest::clear_id()
  {
    _impl_.id_ = 0;
  }
  inline int32_t GetUserRequest::_internal_id() const
  {
    return _impl_.id_;
  }
  inline int32_t GetUserRequest::id() const
  {
    // @@protoc_insertion_point(field_get:user.GetUserRequest.id)
    return _internal_id();
  }
  inline void GetUserRequest::_internal_set_id(int32_t value)
  {

    _impl_.id_ = value;
  }
  inline void GetUserRequest::set_id(int32_t value)
  {
    _internal_set_id(value);
    // @@protoc_insertion_point(field_set:user.GetUserRequest.id)
  }

  // -------------------------------------------------------------------

  // DeleteUserRequest

  // int32 id = 1;
  inline void DeleteUserRequest::clear_id()
  {
    _impl_.id_ = 0;
  }
  inline int32_t DeleteUserRequest::_internal_id() const
  {
    return _impl_.id_;
  }
  inline int32_t DeleteUserRequest::id() const
  {
    // @@protoc_insertion_point(field_get:user.DeleteUserRequest.id)
    return _internal_id();
  }
  inline void DeleteUserRequest::_internal_set_id(int32_t value)
  {

    _impl_.id_ = value;
  }
  inline void DeleteUserRequest::set_id(int32_t value)
  {
    _internal_set_id(value);
    // @@protoc_insertion_point(field_set:user.DeleteUserRequest.id)
  }

  // -------------------------------------------------------------------

  // UserResponse

  // .user.User user = 1;
  inline bool UserResponse::_internal_has_user() const
  {
    return this != internal_default_instance() && _impl_.user_ != nullptr;
  }
  inline bool UserResponse::has_user() const
  {
    return _internal_has_user();
  }
  inline void UserResponse::clear_user()
  {
    if (GetArenaForAllocation() == nullptr && _impl_.user_ != nullptr)
    {
      delete _impl_.user_;
    }
    _impl_.user_ = nullptr;
  }
  inline const ::user::User &UserResponse::_internal_user() const
  {
    const ::user::User *p = _impl_.user_;
    return p != nullptr ? *p : reinterpret_cast<const ::user::User &>(::user::_User_default_instance_);
  }
  inline const ::user::User &UserResponse::user() const
  {
    // @@protoc_insertion_point(field_get:user.UserResponse.user)
    return _internal_user();
  }
  inline void UserResponse::unsafe_arena_set_allocated_user(
      ::user::User *user)
  {
    if (GetArenaForAllocation() == nullptr)
    {
      delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite *>(_impl_.user_);
    }
    _impl_.user_ = user;
    if (user)
    {
    }
    else
    {
    }
    // @@protoc_insertion_point(field_unsafe_arena_set_allocated:user.UserResponse.user)
  }
  inline ::user::User *UserResponse::release_user()
  {

    ::user::User *temp = _impl_.user_;
    _impl_.user_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
    auto *old = reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite *>(temp);
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    if (GetArenaForAllocation() == nullptr)
    {
      delete old;
    }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
    if (GetArenaForAllocation() != nullptr)
    {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
#endif // !PROTOBUF_FORCE_COPY_IN_RELEASE
    return temp;
  }
  inline ::user::User *UserResponse::unsafe_arena_release_user()
  {
    // @@protoc_insertion_point(field_release:user.UserResponse.user)

    ::user::User *temp = _impl_.user_;
    _impl_.user_ = nullptr;
    return temp;
  }
  inline ::user::User *UserResponse::_internal_mutable_user()
  {

    if (_impl_.user_ == nullptr)
    {
      auto *p = CreateMaybeMessage<::user::User>(GetArenaForAllocation());
      _impl_.user_ = p;
    }
    return _impl_.user_;
  }
  inline ::user::User *UserResponse::mutable_user()
  {
    ::user::User *_msg = _internal_mutable_user();
    // @@protoc_insertion_point(field_mutable:user.UserResponse.user)
    return _msg;
  }
  inline void UserResponse::set_allocated_user(::user::User *user)
  {
    ::PROTOBUF_NAMESPACE_ID::Arena *message_arena = GetArenaForAllocation();
    if (message_arena == nullptr)
    {
      delete _impl_.user_;
    }
    if (user)
    {
      ::PROTOBUF_NAMESPACE_ID::Arena *submessage_arena =
          ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(user);
      if (message_arena != submessage_arena)
      {
        user = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
            message_arena, user, submessage_arena);
      }
    }
    else
    {
    }
    _impl_.user_ = user;
    // @@protoc_insertion_point(field_set_allocated:user.UserResponse.user)
  }

  // -------------------------------------------------------------------

  // DeleteUserResponse

  // bool success = 1;
  inline void DeleteUserResponse::clear_success()
  {
    _impl_.success_ = false;
  }
  inline bool DeleteUserResponse::_internal_success() const
  {
    return _impl_.success_;
  }
  inline bool DeleteUserResponse::success() const
  {
    // @@protoc_insertion_point(field_get:user.DeleteUserResponse.success)
    return _internal_success();
  }
  inline void DeleteUserResponse::_internal_set_success(bool value)
  {

    _impl_.success_ = value;
  }
  inline void DeleteUserResponse::set_success(bool value)
  {
    _internal_set_success(value);
    // @@protoc_insertion_point(field_set:user.DeleteUserResponse.success)
  }

  // -------------------------------------------------------------------

  // UserList

  // repeated .user.User users = 1;
  inline int UserList::_internal_users_size() const
  {
    return _impl_.users_.size();
  }
  inline int UserList::users_size() const
  {
    return _internal_users_size();
  }
  inline void UserList::clear_users()
  {
    _impl_.users_.Clear();
  }
  inline ::user::User *UserList::mutable_users(int index)
  {
    // @@protoc_insertion_point(field_mutable:user.UserList.users)
    return _impl_.users_.Mutable(index);
  }
  inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::user::User> *
  UserList::mutable_users()
  {
    // @@protoc_insertion_point(field_mutable_list:user.UserList.users)
    return &_impl_.users_;
  }
  inline const ::user::User &UserList::_internal_users(int index) const
  {
    return _impl_.users_.Get(index);
  }
  inline const ::user::User &UserList::users(int index) const
  {
    // @@protoc_insertion_point(field_get:user.UserList.users)
    return _internal_users(index);
  }
  inline ::user::User *UserList::_internal_add_users()
  {
    return _impl_.users_.Add();
  }
  inline ::user::User *UserList::add_users()
  {
    ::user::User *_add = _internal_add_users();
    // @@protoc_insertion_point(field_add:user.UserList.users)
    return _add;
  }
  inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::user::User> &
  UserList::users() const
  {
    // @@protoc_insertion_point(field_list:user.UserList.users)
    return _impl_.users_;
  }

  // -------------------------------------------------------------------

  // UpdateUserRequest

  // int32 id = 1;
  inline void UpdateUserRequest::clear_id()
  {
    _impl_.id_ = 0;
  }
  inline int32_t UpdateUserRequest::_internal_id() const
  {
    return _impl_.id_;
  }
  inline int32_t UpdateUserRequest::id() const
  {
    // @@protoc_insertion_point(field_get:user.UpdateUserRequest.id)
    return _internal_id();
  }
  inline void UpdateUserRequest::_internal_set_id(int32_t value)
  {

    _impl_.id_ = value;
  }
  inline void UpdateUserRequest::set_id(int32_t value)
  {
    _internal_set_id(value);
    // @@protoc_insertion_point(field_set:user.UpdateUserRequest.id)
  }

  // string name = 2;
  inline void UpdateUserRequest::clear_name()
  {
    _impl_.name_.ClearToEmpty();
  }
  inline const std::string &UpdateUserRequest::name() const
  {
    // @@protoc_insertion_point(field_get:user.UpdateUserRequest.name)
    return _internal_name();
  }
  template <typename ArgT0, typename... ArgT>
  inline PROTOBUF_ALWAYS_INLINE void UpdateUserRequest::set_name(ArgT0 &&arg0, ArgT... args)
  {

    _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:user.UpdateUserRequest.name)
  }
  inline std::string *UpdateUserRequest::mutable_name()
  {
    std::string *_s = _internal_mutable_name();
    // @@protoc_insertion_point(field_mutable:user.UpdateUserRequest.name)
    return _s;
  }
  inline const std::string &UpdateUserRequest::_internal_name() const
  {
    return _impl_.name_.Get();
  }
  inline void UpdateUserRequest::_internal_set_name(const std::string &value)
  {

    _impl_.name_.Set(value, GetArenaForAllocation());
  }
  inline std::string *UpdateUserRequest::_internal_mutable_name()
  {

    return _impl_.name_.Mutable(GetArenaForAllocation());
  }
  inline std::string *UpdateUserRequest::release_name()
  {
    // @@protoc_insertion_point(field_release:user.UpdateUserRequest.name)
    return _impl_.name_.Release();
  }
  inline void UpdateUserRequest::set_allocated_name(std::string *name)
  {
    if (name != nullptr)
    {
    }
    else
    {
    }
    _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.name_.IsDefault())
    {
      _impl_.name_.Set("", GetArenaForAllocation());
    }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:user.UpdateUserRequest.name)
  }

  // string email = 3;
  inline void UpdateUserRequest::clear_email()
  {
    _impl_.email_.ClearToEmpty();
  }
  inline const std::string &UpdateUserRequest::email() const
  {
    // @@protoc_insertion_point(field_get:user.UpdateUserRequest.email)
    return _internal_email();
  }
  template <typename ArgT0, typename... ArgT>
  inline PROTOBUF_ALWAYS_INLINE void UpdateUserRequest::set_email(ArgT0 &&arg0, ArgT... args)
  {

    _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
    // @@protoc_insertion_point(field_set:user.UpdateUserRequest.email)
  }
  inline std::string *UpdateUserRequest::mutable_email()
  {
    std::string *_s = _internal_mutable_email();
    // @@protoc_insertion_point(field_mutable:user.UpdateUserRequest.email)
    return _s;
  }
  inline const std::string &UpdateUserRequest::_internal_email() const
  {
    return _impl_.email_.Get();
  }
  inline void UpdateUserRequest::_internal_set_email(const std::string &value)
  {

    _impl_.email_.Set(value, GetArenaForAllocation());
  }
  inline std::string *UpdateUserRequest::_internal_mutable_email()
  {

    return _impl_.email_.Mutable(GetArenaForAllocation());
  }
  inline std::string *UpdateUserRequest::release_email()
  {
    // @@protoc_insertion_point(field_release:user.UpdateUserRequest.email)
    return _impl_.email_.Release();
  }
  inline void UpdateUserRequest::set_allocated_email(std::string *email)
  {
    if (email != nullptr)
    {
    }
    else
    {
    }
    _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    if (_impl_.email_.IsDefault())
    {
      _impl_.email_.Set("", GetArenaForAllocation());
    }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
    // @@protoc_insertion_point(field_set_allocated:user.UpdateUserRequest.email)
  }

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__
  // -------------------------------------------------------------------

  // -------------------------------------------------------------------

  // -------------------------------------------------------------------

  // -------------------------------------------------------------------

  // -------------------------------------------------------------------

  // -------------------------------------------------------------------

  // -------------------------------------------------------------------

  // @@protoc_insertion_point(namespace_scope)

} // namespace user

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_user_2eproto
